# Generated by Django 3.2.25 on 2025-08-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='freeboard_p_created_5fd753_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-created_at'], name='freeboard_p_categor_ba0612_idx'),
        ),
    ]
