worker_processes 2;

events {
    worker_connections  1024;
    multi_accept on;
    use epoll;  # 리눅스에서 고성능 이벤트 처리
}

http {
    sendfile on;
	keepalive_timeout 15;
	tcp_nodelay on;
	types_hash_max_size 1024;
	
    server {
        listen 80;

        include mime.types;

        locaton /static/ {
            alias /data/static/;
        }

        locaton /media/ {
            alias /data/media/;
        }

        location / {
            proxy_pass django-gunicorn:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
